### PR TITLE
Fix Product URL In Breadcrumbs

### LINKED ISSUE #83: Fix product_url in breadcrumb Schema.org structured data
@sperks38 reported a bug around `product_urls` in the breadcrumb structured data. Triage and fix.

### PR DESCRIPTION
**Pull request by tubbo**
The `storefront_url_for` method doesn't handle models other than taxons,
but the Schema.org helpers use it to render breadcrumb URLs in the
`BreadcrumbList` for any model that's in the breadcrumbs. To prevent
incorrect URLs from showing up in the breadcrumbs, the
`Navigation::Breadcrumbs` class has been modified to accept a model
object as its `:last` parameter, instead of just a name, to be added to
an arbitrary `Navigation::Taxon` created for the purpose of rendering
both the name and URL of the final navigation taxon. This wasn't needed
prior to the introduction of Schema.org's `BreadcrumbList`, because the
final URL of breadcrumbs was always left out. The helper methods that
render the breadcrumbs will continue to leave out the final taxon's URL,
but for breadcrumbs in Schema.org, the URL will now be included.

(#83)

### CODE REVIEW

File: storefront/app/helpers/workarea/storefront/navigation_helper.rb [hunk 1]
```diff
@@ -65,22 +65,25 @@ def link_to_menu(menu)
         end
       end
 
-      def storefront_path_for(taxon)
-        if taxon.url?
-          taxon.url
-        elsif taxon.root?
+      def storefront_path_for(model)
```
Comment (bencrouse) [inline storefront/app/helpers/workarea/storefront/navigation_helper.rb]: This wasn't intended to allow passing any model to it. We should correct it upstream. Where are we calling this without a taxon?

File: storefront/test/helpers/workarea/storefront/schema_org_helper_test.rb [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+        page = create_page
+        url_taxon = create_taxon(url: 'https://www.example.com')
+        navigable_taxon = create_taxon(navigable: page)
+        inventory = create_inventory
+
+        assert_equal(product_url(product, host: Workarea.config.host), breadcrumb_url_for(product))
+        assert_equal(page_url(page, host: Workarea.config.host), breadcrumb_url_for(page))
+        assert_equal('https://www.example.com', breadcrumb_url_for(url_taxon))
+        assert_equal(page_url(page, host: Workarea.config.host), breadcrumb_url_for(navigable_taxon))
+        assert_raises(NoMethodError) { breadcrumb_url_for(inventory) }
```
Comment (tubbo) [inline storefront/test/helpers/workarea/storefront/schema_org_helper_test.rb]: I don't know if we should warn people or render a better error here...the NoMethodError produced when you add something to breadcrumbs that isn't routed at the top level doesn't really tell you much about why it happened...

File: storefront/app/views/layouts/workarea/storefront/application.html.haml [hunk 3]
```diff
@@ -102,7 +102,7 @@
             .breadcrumbs{ role: 'navigation' }
               = yield :breadcrumbs
           - elsif @breadcrumbs.present?
-            = render_schema_org(breadcrumb_list_schema(@breadcrumbs.map { |t| [t.name, storefront_url_for(t)] }))
+            = render_schema_org(breadcrumb_list_schema(@breadcrumbs.map { |t| [t.name, breadcrumb_url_for(t)] }))
```
Comment (bencrouse) [inline storefront/app/views/layouts/workarea/storefront/application.html.haml]: It feels like the problem should be handled more gracefully upstream so we don't have to do all the string munging to figure out the route. Where is the bad data coming from?

File: storefront/test/helpers/workarea/storefront/schema_org_helper_test.rb (hunk 2 above)
Comment (bencrouse) [reply storefront/test/helpers/workarea/storefront/schema_org_helper_test.rb]: I agree, I think we should look at what the data is upstream causing this situation and see if we can change that.

File: core/app/models/workarea/navigation/breadcrumbs.rb [hunk 4]
```diff
@@ -13,7 +13,7 @@ def self.from_global_id(via, last: nil)
 
       def initialize(navigable, last: nil)
         @navigable = navigable
-        @last = Taxon.new(name: last) if last.present?
+        @last = Taxon.new(name: last.name, navigable: last) if last.present?
```
Comment (bencrouse) [inline core/app/models/workarea/navigation/breadcrumbs.rb]: Can we have this gracefully degrade so keep the same API? Then we don't need to change the `ProductViewModel`.
```suggestion
        @last = if last.try(:navigable?)
          Taxon.new(name: last.name, navigable: last)
        elsif last.present?
          Taxon.new(name: last)
        end
```

File: core/test/models/workarea/navigation/breadcrumbs_test.rb [hunk 5]
```diff
@@ -23,10 +23,12 @@ def test_collection
       end
 
       def test_last
```
Comment (bencrouse) [inline core/test/models/workarea/navigation/breadcrumbs_test.rb]: After the suggestion above, you should be able to reduce this to just testing a navigable as `last`.

File: storefront/app/view_models/workarea/storefront/product_view_model.rb [hunk 6]
```diff
@@ -1,7 +1,6 @@
 module Workarea
   module Storefront
     class ProductViewModel < ApplicationViewModel
-
```
Comment (bencrouse) [inline storefront/app/view_models/workarea/storefront/product_view_model.rb]: Can remove changes to this file after suggestion above.

**Comment by bencrouse** [comment]
This is coming along well!

File: storefront/app/view_models/workarea/storefront/product_view_model.rb (hunk 6 above)
Comment (tubbo) [reply storefront/app/view_models/workarea/storefront/product_view_model.rb]: that would kinda defeat the purpose of all this, because a string isn't `.navigable?`, so we still need to pass the full product model into the breadcrumbs as `:last` in order to generate the right URL.

File: core/app/models/workarea/navigation/breadcrumbs.rb (hunk 4 above)
Comment (tubbo) [reply core/app/models/workarea/navigation/breadcrumbs.rb]: I guess I'm OK with this but again this defeats the purpose of the fix to schema.org helpers, which is what this ticket was about in the first place. Definitely would help with backwards-compatibility in a patch, though, so I think this is OK...but I can't undo the changes to ProductViewModel as a result since it needs to pass in the full model so the final Taxon knows what URL to generate in `storefront_path_for`.

File: core/app/models/workarea/navigation/breadcrumbs.rb [hunk 7]
```diff
@@ -13,7 +13,11 @@ def self.from_global_id(via, last: nil)
 
       def initialize(navigable, last: nil)
         @navigable = navigable
-        @last = Taxon.new(name: last) if last.present?
+        @last = if last.try(:navigable?)
```
Comment (bencrouse) [inline core/app/models/workarea/navigation/breadcrumbs.rb]: Judging from the build, I think I forgot we'd need a `def navigable?` in the `Navigable` module.

File: storefront/app/view_models/workarea/storefront/product_view_model.rb (hunk 6 above)
Comment (bencrouse) [reply storefront/app/view_models/workarea/storefront/product_view_model.rb]: Do the tests pass without the change?

Comment (tubbo) [reply storefront/app/view_models/workarea/storefront/product_view_model.rb]: fixed it by checking whether `last.class.includes? Navigable` so we don't have to write an additional method.

File: storefront/app/view_models/workarea/storefront/product_view_model.rb [hunk 8]
```diff
@@ -18,12 +17,12 @@ def breadcrumbs
           if options[:via].present?
             Navigation::Breadcrumbs.from_global_id(
               options[:via],
-              last: model.name
+              last: model
```
Comment (bencrouse) [inline storefront/app/view_models/workarea/storefront/product_view_model.rb]: So why do this unnecessary change? Better to reduce churn for upgrades if this doesn't affect anything.

Comment (tubbo) [reply storefront/app/view_models/workarea/storefront/product_view_model.rb]: this isn't unnecessary, it's what fixes the schema

Comment (tubbo) [reply storefront/app/view_models/workarea/storefront/product_view_model.rb]: again, this isn't unnecessary. i wrote in an above conversation:

> that would kinda defeat the purpose of all this, because a string isn't `.navigable?`, so we still need to pass the full product model into the breadcrumbs as `:last` in order to generate the right URL.

basically, i need `:last` to be a model in order for the Schema.org helper methods to render the right URL for the last Taxon.
