### PR TITLE
Use Current Host For Direct Upload CORS Headers

### LINKED ISSUE #19: Direct Uploads Fail Locally
**Describe the bug**
When directly uploading assets, either on `/admin/content_assets` or in a content block itself, and the S3 bucket is configured properly, assets can still fail to upload if the `Workarea.config.host` does not match 

**To Reproduce**
1. Configure your app with S3 secrets and a `config.host` like `example.com`. 
2. Go to `/admin/content_assets` and try to upload an asset
3. You'll get a "Something Went Wrong" message, and CORS warnings in the JS console

**Expected behavior**
The asset should upload successfully.

**Workarea Setup (please complete the following information):**
- Workarea v3.4.14

### PR DESCRIPTION
**Pull request by tubbo**
Direct uploads can fail locally if your `Workarea.config.host` is not
set to the domain you are currently using in the browser. To prevent
this, instead of reading from the configuration when ensuring CORS
headers on the S3 bucket, use the `ActionDispatch::Request` from the
controller to determine the correct URL for CORS in this instance.
Addresses a problem whereby changing the domain (either accidentally or
on-purpose) causes direct uploads to fail, since it can't create the
proper CORS headers needed to transmit files into the bucket directly.

Fixes #19

### CODE REVIEW

File: admin/app/controllers/workarea/admin/content_assets_controller.rb [hunk 1]
```diff
@@ -7,7 +7,9 @@ class Admin::ContentAssetsController < Admin::ApplicationController
     after_action :track_index_filters, only: :index
 
     def index
-      DirectUpload.ensure_cors! if Configuration::S3.configured? && !request.xhr?
+      if Configuration::S3.configured? && !request.xhr?
+        DirectUpload.ensure_cors!(request)
```
[the remark this answers is not in the document]
Comment (tubbo) [reply admin/app/controllers/workarea/admin/content_assets_controller.rb]: I need the port sometimes.

File: admin/app/controllers/workarea/admin/direct_uploads_controller.rb [hunk 2]
```diff
@@ -2,7 +2,7 @@ module Workarea
   module Admin
     class DirectUploadsController < Admin::ApplicationController
       def product_images
-        DirectUpload.ensure_cors! if Configuration::S3.configured?
+        DirectUpload.ensure_cors!(request.host) if Configuration::S3.configured?
```
[the remark this answers is not in the document]
Comment (tubbo) [reply admin/app/controllers/workarea/admin/direct_uploads_controller.rb]: yup, that was a mistake

File: core/test/services/workarea/direct_upload_test.rb [hunk 3]
```diff
@@ -46,6 +46,64 @@ def test_validation
       refute(direct_upload.valid?)
     end
 
+    def test_ensure_cors
+      original_host = Workarea.config.host
+      Workarea.config.host = 'test.host'
+      dev_request = mock(
```
Comment (bencrouse) [inline core/test/services/workarea/direct_upload_test.rb]: Can we use `ActionDispatch::TestRequest` since Rails provides that for this kind of usecase? https://api.rubyonrails.org/v5.1/classes/ActionDispatch/TestRequest.html

File: core/test/services/workarea/direct_upload_test.rb [hunk 4]
```diff
@@ -46,6 +46,64 @@ def test_validation
...
+            'AllowedHeader' => '*'
+          }
+        ]
+      ).returns(true)
+
+
+      assert(DirectUpload.ensure_cors!)
+      assert(DirectUpload.ensure_cors!(dev_request))
+      assert(DirectUpload.ensure_cors!(prod_request))
+    ensure
```
Comment (bencrouse) [inline core/test/services/workarea/direct_upload_test.rb]: Don't forget about `Workarea.with_config do |config|`!

File: core/app/services/workarea/direct_upload.rb [hunk 5]
```diff
@@ -2,17 +2,25 @@ module Workarea
   class DirectUpload
     class InvalidTypeError < RuntimeError; end
 
-    def self.ensure_cors!
-      url = "http#{Rails.application.config.force_ssl ? 's' : ''}://"
-      url += Workarea.config.host
+    def self.ensure_cors!(request = nil)
```
Comment (bencrouse) [inline core/app/services/workarea/direct_upload.rb]: Should we just make the url a required arg if it's going to be used everywhere? Then we could clean up that `if` clutter below! Something like: `DirectUpload.ensure_cors!(request.url)`. `request.url` gives me `http://localhost:3000`, which is everything we'd need here. That would also alleviate the need to mock in the test.

Comment (tubbo) [reply core/app/services/workarea/direct_upload.rb]: I'm down with that.

File: core/app/services/workarea/direct_upload.rb [hunk 6]
```diff
@@ -2,15 +2,14 @@ module Workarea
   class DirectUpload
     class InvalidTypeError < RuntimeError; end
 
-    def self.ensure_cors!
-      url = "http#{Rails.application.config.force_ssl ? 's' : ''}://"
-      url += Workarea.config.host
+    def self.ensure_cors!(url)
+      uri = URI.parse(url)
```
Comment (bencrouse) [inline core/app/services/workarea/direct_upload.rb]: We can just get rid of this right? No need for just the host below, might as well use the full URL as the ID in the config.

**Comment by meowsus** [comment]
[Direct Uploads Fail Locally](https://trello.com/c/jjQp5hT3/3-direct-uploads-fail-locally)
